### ISSUE TITLE
连接的url 跟主页的url不一致，且无法使用demo

### ISSUE THREAD

**Issue by 541573560** [huobiapi/Websocket-Python3-demo#1]
demo：
ws = create_connection("wss://api.huobipro.com/ws")
主页：
Pro 站行情请求地址为：wss://api.huobi.pro/ws
HADAX 站行情请求地址为：wss://api.hadax.com/ws

**Comment by Harvey518** [comment]
好像一直连不上啊，用了新地址也连不上

**Comment by 541573560** [comment]
> 好像一直连不上啊，用了新地址也连不上

我找到新的 url 了，应该是没有及时更新 文档 ，需要我发给你嘛？

**Comment by kuskyfei** [comment]
> > 好像一直连不上啊，用了新地址也连不上
> 
> 我找到新的 url 了，应该是没有及时更新 文档 ，需要我发给你嘛？

麻烦发我一个新的地址吧,我按照wss://api.huobi.pro/ws这个好像也行

**Comment by kuskyfei** [comment]
@541573560 

> > 好像一直连不上啊，用了新地址也连不上
> 
> 我找到新的 url 了，应该是没有及时更新 文档 ，需要我发给你嘛？

麻烦发我一个新的地址吧

**Comment by 541573560** [comment]
> @541573560
> 
> > > 好像一直连不上啊，用了新地址也连不上
> > 
> > 
> > 我找到新的 url 了，应该是没有及时更新 文档 ，需要我发给你嘛？
> 
> 麻烦发我一个新的地址吧

wss://www.hbg.com/-/s/pro/ws

**Comment by honunu** [comment]
api.huobi.pro 连不上，用境外的服务器就能连上，是需要代理吗

**Comment by phpcolt** [comment]
使用代理链接时而好时而坏，主要看运气，直接用境外的服务器弄吧

**Comment by huobiapi** [comment]
请使用中国大陆以外的服务器访问火币 API，root url 请使用 api.huobi.pro
