### ISSUE TITLE
請教 demo 中的訂閱一直報錯"sub invalid topic"

### ISSUE THREAD

**Issue by ShihWeiHuang** [huobiapi/Websocket-Python3-demo#2]
訂閱參數'accounts' 可以 
{
        'op':'sub',
        'topic':'accounts',
        'id':'fdsafddd3'
        }

，設定成其他都不可以
{
        'op':'sub',
        'topic':'market.btcusdt.kline.1min',
        'id':'fdsafddd3'
        }
改成這種型式也不行
{
  "sub": "market.btcusdt.kline.1min",
  "id": "id1"
}

market.tickers 這個也會報錯
{
        'op':'sub',
        'topic':'market.tickers',
        'id':'fdsafddd3'
        }

# 订阅或取消订阅

websockClient().start_websocket(func='sub_padding', data=datasymbols, authdata=authdata)

**Comment by libingnan** [comment]
这个是针对账号及订单的订阅，行情的订阅demo为huobi.py

**Comment by zouzehe** [comment]
行情的订阅这个  wss://api.huobi.pro/ws/v1
