### ISSUE TITLE
鉴权失败

### ISSUE THREAD

**Issue by ddlau** [huobiapi/Websocket-Python3-demo#3]
我在鉴权的时候，始终返回：
`{'err-code': 1002,
 'err-msg': 'internal error : onTextMessage exception',
 'op': 'error',
 'ts': 1545031474522}
`
请问是怎么回事？另外到底是用“api.huobi.pro”还是“api.huobi.com”？

**Comment by zouzehe** [comment]
应该使用 wss://api.huobi.pro/ws/v1

**Comment by ddlau** [comment]
已经OK
