### ISSUE TITLE
Websocket market-depth Huobi

### ISSUE THREAD

**Issue by araa47** [huobiapi/Websocket-Python3-demo#4]
I am currently subscribing to order book WebSockets and using the following "sub":
"market.X.depth.step0", where X is the symbol. What do the step0, step1, step2, step3, step4 and step5 arguments exactly do? Looks like to get the whole order book I need to subscribe to step0.

**Comment by huobiapi** [comment]
‘stepX’ means merging depth data according to the number of decimal places, for more details, see https://api.huobi.pro/market/symbols
